filebeat.inputs:
- type: log
  enabled: true

  paths:
    - /var/log/gerador.log
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  