"""tabela de associacao entre perfil-permissao

Revision ID: 12e0deddac06
Revises: 34e85c24a6dd
Create Date: 2025-08-31 00:54:07.070854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e0deddac06'
down_revision: Union[str, Sequence[str], None] = '34e85c24a6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_permissao',
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('permissao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], )
    )
    op.drop_column('empresas', 'gestores')
    op.drop_column('perfis', 'permissoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfis', sa.Column('permissoes', sa.VARCHAR(), nullable=True))
    op.add_column('empresas', sa.Column('gestores', sa.VARCHAR(), nullable=True))
    op.drop_table('perfil_permissao')
    op.drop_table('permissoes')
    # ### end Alembic commands ###
